theme: jekyll-theme-cayman
name: "my-website"
navbar:
  title: "My Website"
  left:
    - text: "Home"
      href: index.html
    - text: "Beer Study"
      href: beer.html
    - text: "About"
      href: about.html
