<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Thad Schwebke" />


<title>Beer Study</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Thad Schwebke</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="beer_shiny.html">Beer Shiny</a>
</li>
<li>
  <a href="beer_analysis.html">Beer Study</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Beer Study</h1>
<h4 class="author">Thad Schwebke</h4>
<h4 class="date">3/21/2020</h4>

</div>


<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>You can assume that your audience is the CEO and CFO of Budweiser (your client) and that they only have had one class in statistics and have indicated that you cannot take more than 7 minutes of their time. 20% of your grade will be based on the presentation.</p>
<p>They have hired you to address the 9 questions / items described in the next section. Beyond those general questions you may and should speculate / anticipate what may be of interest to them.</p>
</div>
<div id="deliverables" class="section level2">
<h2>Deliverables</h2>
<ol style="list-style-type: upper-alpha">
<li>A GitHub repository (Due Saturday March 7th 11:59pm CST</li>
</ol>
<p>The GitHub repo should contain the following items and a link to the GitHub repo should be placed on a Word Doc (or PDF) and submitted to 2DS for Unit 8.</p>
<p>The final repo which will be checked after 11:59pm CST March 7th should contain:</p>
<ol style="list-style-type: decimal">
<li>An RMarkdown file containing the following:</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>The introduction needs to be written as if you are presenting the work to the CEO and CFO of Budweiser (your client) and that they only have had one class in statistics. If it sounds like a student presentation, that is not acceptable. You may assume that the CEO and CFO gave you the data and gave you the directive to report any interesting finding that you may uncover through your analysis.</p></li>
<li><p>Briefly explain the purpose of the code. The explanations should appear as a sentence or two before or after the code chunk. Even though you will not be hiding the code chunks (so that I can see the code), you need to assume that the client can’t see them.</p></li>
<li><p>Use R to address the 9 questions / items below:</p></li>
</ol>
<ol style="list-style-type: decimal">
<li><p>How many breweries are present in each state?</p></li>
<li><p>Merge beer data with the breweries data. Print the first 6 observations and the last six observations to check the merged file. (RMD only, this does not need to be included in the presentation or the deck.)</p></li>
<li><p>Address the missing values in each column.</p></li>
<li><p>Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.</p></li>
<li><p>Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer?</p></li>
<li><p>Comment on the summary statistics and distribution of the ABV variable.</p></li>
<li><p>Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot. Make your best judgment of a relationship and EXPLAIN your answer.</p></li>
<li><p>Budweiser would also like to investigate the difference with respect to IBU and ABV between IPAs (India Pale Ales) and other types of Ale (any beer with “Ale” in its name other than IPA). You decide to use KNN classification to investigate this relationship. Provide statistical evidence one way or the other. You can of course assume your audience is comfortable with percentages … KNN is very easy to understand conceptually.</p></li>
</ol>
<p>In addition, while you have decided to use KNN to investigate this relationship (KNN is required) you may also feel free to supplement your response to this question with any other methods or techniques you have learned. Creativity and alternative solutions are always encouraged.</p>
<ol start="9" style="list-style-type: decimal">
<li>Knock their socks off! Find one other useful inference from the data that you feel Budweiser may be able to find value in. You must convince them why it is important and back up your conviction with appropriate statistical evidence.</li>
</ol>
<p>Directives on RMD File: i. Give clear, explicit answers to the questions. Just the code to answer the questions is not nearly enough, even if the code is correct and gives the correct answer. You must state the answer in a complete sentence outside the code chunk.</p>
<ol start="2" style="list-style-type: lower-roman">
<li>Conclusion to the project. Summarize your findings from this exercise. The file must be readable in GitHub. In other words, don’t forget to keep the md file!!</li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li><p>Knit HTML file.<br />
In fact, you will also upload the knit html file to GitHub as well. This will allow for plots and tables to supplement your answers (part e) to the 7 questions below. You are already making an Rmd file, we should take advantage of it and knit a nice presentation of the project!</p></li>
<li><p>Codebook, Both CSV files and a ReadMe.md The Readme file describes the purpose of the project and codebook. The repo can be structured however you like, but it should make sense and be easily navigated.</p></li>
<li><p>PPT Slides Described more below and should have the link to your You Tube presentation … described further below as well.)</p></li>
</ol>
<p>B. UNIT 8 Live Session: EDA Each team will need to meet with the professor and present their EDA in Unit 8. It is up to the teams and the professor when and how to set up these meetings. They may be during the schedule live session time, but given time constraints, some teams will need to schedule times outside of their scheduled live session time. With that said, these are one on one meetings between each team and the professor. Your only scheduled time commitment in Unit 8 is to attend this 10ish minute meeting with your professor. The rest of the time is reserved to work on your project with your partner. Your goal is to present your EDA (Answers to Questions 1,3,4,5,6,7). At this point, teams should have presentation quality slides and presentation prepared. Responses to each of the questions listed above should be prepared and addressed in this meeting.</p>
<p>The grade for this portion is based on the slide deck and the presentation. If the team is prepared and delivers a well-practiced presentation it should be easy to earn close to a 100% here.</p>
<ol start="2" style="list-style-type: upper-alpha">
<li>Unit 9 Live Session: Q &amp; A.<br />
During Live Session for Unit 9, the professor will be available for a live Q &amp; A about the project / presentation. Attendance at this live session is not required (attendance is optional). NOTE ABOUT POWERPOINT … You may use the same powerpoint or develop them separately. I would imagine that even if you develop the powerpoint together that each student’s final powerpoint will be a little different just based on individual presentation style. Everyone has their own unique style and delivery.</li>
</ol>
<p>C. Final YouTube Video Each team member will need to record and upload to YouTube a 7-minute or less presentation of your findings. At this point you should know your presentation backwards and forwards. If you trip up too much in your recording, you should start over until you have a very polished presentation that does not exceed 7 minutes.</p>
<p>To record you can download Camtasia (free trial) which is a video software available at <a href="https://www.techsmith.com/video-editor.html" class="uri">https://www.techsmith.com/video-editor.html</a> or use your preferred screen capture software (like QuickTime if you have a Mac.) The presentation slides that include a link to your video should be in the Case Study Github repo as well as on the Google Doc provided by your professor. The goal is to communicate the findings of the project in a clear, concise and scientific manner. Also, uploading to YouTube is not difficult. Here is a YouTube video to help: <a href="https://www.youtube.com/watch?v=VtF2AgFSLAw" class="uri">https://www.youtube.com/watch?v=VtF2AgFSLAw</a> Your professor will make the Google Doc link available to everyone in the class so that your peers can benefit from your work and so that you can benefit from theirs. Student’s presentation links will be available for a week at which time you may take your video off of YouTube if you wish.</p>
</div>
<div id="collaboration-and-peer-review" class="section level2">
<h2>Collaboration and Peer Review</h2>
<p>This will be a team project. We expect that all team members will do equal work and give their best to advance the knowledge of both themselves and their teammate. All members will need to push, add, commit, and pull to GitHub. This is a collaborative project, be sure and communicate early and often; mutual respect is key.</p>
<p>You will be providing two peer reviews that will be submitted to 2DS in Unit 8 and Unit 9 under: Project 1: EDA and Peer Review (by Saturday Feb 29 11:59pm / Unit 8) and Project 1: Final Documentation, Presentation and Peer Review Assignment (by Saturday March 7 11:59pm / Unit 9) . See the Rubric for detailed information on the peer review.</p>
</div>
<div id="eda" class="section level2">
<h2>EDA:</h2>
<p>Questions 1,3,4,5,6,7</p>
</div>
<div id="load-libraries" class="section level2">
<h2>Load Libraries</h2>
<pre class="r"><code>#install.packages(&quot;vctrs&quot;)
library(vctrs)
library(qwraps2)
library(tidyverse) # super library that loads dplyr, ggplot2, lubridate, tidyr, stringr, etc.
library(DataExplorer) # shows missing values by bar and percentage.
library(maps) # used for heat map
library(openintro) # used to convert state abbreviation to full state name
library(gdata)
library(mapdata)
library(mime)
library(treemap) # used for displaying hierarchical data as a set of nested rectangles
library(VIM)
library(inspectdf) #usd for columnwise summary, comparison and visualisation of data frames
library(GGally) # used for ggpairs ()to plot multiple variables, combines different plots into matrix
library(fiftystater)# use to plot 50-state choropleth thematic maps with ggplot2 in R
library(ggthemes)# used for adding some extra themes, geoms, and scales for &#39;ggplot2
library(gridExtra)
library(class)
library(broom)
library(caret)
theme_set(theme_classic())</code></pre>
</div>
<div id="load-data" class="section level2">
<h2>Load Data</h2>
<pre class="r"><code>beers_df &lt;- read.csv(&quot;D:/GitHubRepo/tschwebke.github.io/data/Beers.csv&quot;)
breweries_df &lt;-
  read.csv(&quot;D:/GitHubRepo/tschwebke.github.io/data/Breweries.csv&quot;) </code></pre>
</div>
<div id="inspect-the-data" class="section level2">
<h2>Inspect the data</h2>
<pre class="r"><code>#View(beers_df) # view the complete dataframe
names(beers_df) # view the variable names</code></pre>
<pre><code>## [1] &quot;Name&quot;       &quot;Beer_ID&quot;    &quot;ABV&quot;        &quot;IBU&quot;        &quot;Brewery_id&quot;
## [6] &quot;Style&quot;      &quot;Ounces&quot;</code></pre>
<pre class="r"><code>dim(beers_df) # view the dimensions of the data</code></pre>
<pre><code>## [1] 2410    7</code></pre>
<pre class="r"><code>str(beers_df) # view the structure of the data</code></pre>
<pre><code>## &#39;data.frame&#39;:    2410 obs. of  7 variables:
##  $ Name      : Factor w/ 2305 levels &quot;#001 Golden Amber Lager&quot;,..: 1638 577 1705 1842 1819 268 1160 758 1093 486 ...
##  $ Beer_ID   : int  1436 2265 2264 2263 2262 2261 2260 2259 2258 2131 ...
##  $ ABV       : num  0.05 0.066 0.071 0.09 0.075 0.077 0.045 0.065 0.055 0.086 ...
##  $ IBU       : int  NA NA NA NA NA NA NA NA NA NA ...
##  $ Brewery_id: int  409 178 178 178 178 178 178 178 178 178 ...
##  $ Style     : Factor w/ 100 levels &quot;&quot;,&quot;Abbey Single Ale&quot;,..: 19 18 16 12 16 80 18 22 18 12 ...
##  $ Ounces    : num  12 12 12 12 12 12 12 12 12 12 ...</code></pre>
<pre class="r"><code>head(beers_df, n = 5) # view the first 5 records</code></pre>
<pre><code>##                  Name Beer_ID   ABV IBU Brewery_id
## 1            Pub Beer    1436 0.050  NA        409
## 2         Devil&#39;s Cup    2265 0.066  NA        178
## 3 Rise of the Phoenix    2264 0.071  NA        178
## 4            Sinister    2263 0.090  NA        178
## 5       Sex and Candy    2262 0.075  NA        178
##                            Style Ounces
## 1            American Pale Lager     12
## 2        American Pale Ale (APA)     12
## 3                   American IPA     12
## 4 American Double / Imperial IPA     12
## 5                   American IPA     12</code></pre>
<pre class="r"><code>tail(beers_df, n = 5) # view the last 5 records</code></pre>
<pre><code>##                      Name Beer_ID   ABV IBU Brewery_id                    Style
## 2406            Belgorado     928 0.067  45        425              Belgian IPA
## 2407        Rail Yard Ale     807 0.052  NA        425 American Amber / Red Ale
## 2408      B3K Black Lager     620 0.055  NA        425              Schwarzbier
## 2409  Silverback Pale Ale     145 0.055  40        425  American Pale Ale (APA)
## 2410 Rail Yard Ale (2009)      84 0.052  NA        425 American Amber / Red Ale
##      Ounces
## 2406     12
## 2407     12
## 2408     12
## 2409     12
## 2410     12</code></pre>
<pre class="r"><code>summary(beers_df) # view basic model data i.e. min, max, mdedium, mean, etc.</code></pre>
<pre><code>##                      Name         Beer_ID            ABV         
##  Nonstop Hef Hop       :  12   Min.   :   1.0   Min.   :0.00100  
##  Dale&#39;s Pale Ale       :   6   1st Qu.: 808.2   1st Qu.:0.05000  
##  Oktoberfest           :   6   Median :1453.5   Median :0.05600  
##  Longboard Island Lager:   4   Mean   :1431.1   Mean   :0.05977  
##  1327 Pod&#39;s ESB        :   3   3rd Qu.:2075.8   3rd Qu.:0.06700  
##  Boston Lager          :   3   Max.   :2692.0   Max.   :0.12800  
##  (Other)               :2376                    NA&#39;s   :62       
##       IBU           Brewery_id                               Style     
##  Min.   :  4.00   Min.   :  1.0   American IPA                  : 424  
##  1st Qu.: 21.00   1st Qu.: 94.0   American Pale Ale (APA)       : 245  
##  Median : 35.00   Median :206.0   American Amber / Red Ale      : 133  
##  Mean   : 42.71   Mean   :232.7   American Blonde Ale           : 108  
##  3rd Qu.: 64.00   3rd Qu.:367.0   American Double / Imperial IPA: 105  
##  Max.   :138.00   Max.   :558.0   American Pale Wheat Ale       :  97  
##  NA&#39;s   :1005                     (Other)                       :1298  
##      Ounces     
##  Min.   : 8.40  
##  1st Qu.:12.00  
##  Median :12.00  
##  Mean   :13.59  
##  3rd Qu.:16.00  
##  Max.   :32.00  
## </code></pre>
<pre class="r"><code>plot_missing(beers_df) #shows missing values using package DataExplorer</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code>names(breweries_df) # view the variable names</code></pre>
<pre><code>## [1] &quot;Brew_ID&quot; &quot;Name&quot;    &quot;City&quot;    &quot;State&quot;</code></pre>
<pre class="r"><code>dim(breweries_df) # view the dimensions of the data</code></pre>
<pre><code>## [1] 558   4</code></pre>
<pre class="r"><code>str(breweries_df) # view the structure of the data</code></pre>
<pre><code>## &#39;data.frame&#39;:    558 obs. of  4 variables:
##  $ Brew_ID: int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Name   : Factor w/ 551 levels &quot;10 Barrel Brewing Company&quot;,..: 355 12 266 319 201 136 227 477 59 491 ...
##  $ City   : Factor w/ 384 levels &quot;Abingdon&quot;,&quot;Abita Springs&quot;,..: 228 200 122 299 300 62 91 48 152 136 ...
##  $ State  : Factor w/ 51 levels &quot; AK&quot;,&quot; AL&quot;,&quot; AR&quot;,..: 24 18 20 5 5 41 6 23 23 23 ...</code></pre>
<pre class="r"><code>head(breweries_df, n = 5) # view the first 5 records</code></pre>
<pre><code>##   Brew_ID                      Name          City State
## 1       1        NorthGate Brewing    Minneapolis    MN
## 2       2 Against the Grain Brewery    Louisville    KY
## 3       3  Jack&#39;s Abby Craft Lagers    Framingham    MA
## 4       4 Mike Hess Brewing Company     San Diego    CA
## 5       5   Fort Point Beer Company San Francisco    CA</code></pre>
<pre class="r"><code>tail(breweries_df, n = 5) # view the last 5 records</code></pre>
<pre><code>##     Brew_ID                          Name          City State
## 554     554           Covington Brewhouse     Covington    LA
## 555     555               Dave&#39;s Brewfarm        Wilson    WI
## 556     556         Ukiah Brewing Company         Ukiah    CA
## 557     557       Butternuts Beer and Ale Garrattsville    NY
## 558     558 Sleeping Lady Brewing Company     Anchorage    AK</code></pre>
<pre class="r"><code>summary(breweries_df) # view basic model data i.e. min, max, mdedium, mean, etc.</code></pre>
<pre><code>##     Brew_ID                           Name           City         State    
##  Min.   :  1.0   Blackrocks Brewery     :  2   Portland: 17    CO    : 47  
##  1st Qu.:140.2   Blue Mountain Brewery  :  2   Boulder :  9    CA    : 39  
##  Median :279.5   Lucette Brewing Company:  2   Chicago :  9    MI    : 32  
##  Mean   :279.5   Oskar Blues Brewery    :  2   Seattle :  9    OR    : 29  
##  3rd Qu.:418.8   Otter Creek Brewing    :  2   Austin  :  8    TX    : 28  
##  Max.   :558.0   Sly Fox Brewing Company:  2   Denver  :  8    PA    : 25  
##                  (Other)                :546   (Other) :498   (Other):358</code></pre>
<pre class="r"><code>plot_missing(breweries_df) #shows missing values using package DataExplorer</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-2-2.png" width="672" /></p>
<pre class="r"><code>brewery_dupes &lt;-
  as.character(breweries_df[which(duplicated(as.character(breweries_df$Name))), &quot;Name&quot;]) # Check for duplicates  breweries names
breweries_df %&gt;% filter(Name == &quot;Summit Brewing Company&quot;)  # Brew_ID, City (St. Paul, St Paul)</code></pre>
<pre><code>##   Brew_ID                   Name     City State
## 1      59 Summit Brewing Company St. Paul    MN
## 2     139 Summit Brewing Company  St Paul    MN</code></pre>
<pre class="r"><code>breweries_df %&gt;% filter(Name == &quot;Lucette Brewing Company&quot;) # Brew_ID, City (Menominee, Menominie)</code></pre>
<pre><code>##   Brew_ID                    Name      City State
## 1     378 Lucette Brewing Company Menominee    WI
## 2     457 Lucette Brewing Company Menominie    WI</code></pre>
<pre class="r"><code>breweries_df$City &lt;-
  str_replace_all(breweries_df$City, &quot;St. Paul&quot;, &quot;St Paul&quot;) ## sync spelling
breweries_df$City &lt;-
  str_replace_all(breweries_df$City, &quot;Menominee&quot;, &quot;Menominie&quot;) ## sync spelling</code></pre>
</div>
<div id="sanitize-variable-names-in-data-sets" class="section level2">
<h2>Sanitize Variable Names In Data Sets</h2>
<pre class="r"><code>options(show.error.messages = FALSE)
try(breweries_df &lt;-
      rename(breweries_df, Brewery_id = Brew_ID))
# changed col or variable name to match both data set.
try(breweries_df &lt;-
      rename(breweries_df, Brewery_Name = Name))
#changed col or variable name
try(beers_df &lt;-
      rename(beers_df, Beer_Name = Name))
#changed col or variable name
options(show.error.messages = TRUE)</code></pre>
</div>
<div id="get-mapping-information" class="section level2">
<h2>Get mapping information</h2>
<pre class="r"><code>states_df &lt;- map_data(&quot;state&quot;) # get US states and their coordinates</code></pre>
</div>
<div id="question-1" class="section level2">
<h2>Question 1:</h2>
<p>How many breweries are present in each state?</p>
<pre class="r"><code>brewery_states_df &lt;-
  breweries_df %&gt;% group_by(State) %&gt;% distinct(Brewery_id) # grouping by State using dplyr package
brewery_count &lt;- aggregate(Brewery_id ~ State, breweries_df, length)
names(brewery_count) &lt;-
  c(&quot;State&quot;, &quot;Breweries&quot;) # replace the col names

brewery_count$State &lt;-
  trim(brewery_count$State, recode.factor = TRUE) # trim white spaces
brewery_count$region &lt;-
  tolower(abbr2state(brewery_count$State)) # change all region to lower case

brewery_map_df &lt;-
  left_join(states_df, brewery_count, by = &quot;region&quot;) # merge state_df and brewery count by region to plot all the state in us map.
state_center &lt;-
  aggregate(
    cbind(long, lat) ~ State,
    data = brewery_map_df,
    FUN = function(x)
      mean(range(x))
  ) # combine lat and long of same repeated state into one long and lat
state_center_region &lt;- brewery_map_df %&gt;% group_by(State) %&gt;%
  summarize_at(vars(long, lat), ~ mean(range(.)))
all.equal(state_center, as.data.frame(state_center_region))</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>library(mapproj) # for coord_map function - projects map in spherical into 2D
ggplot(data = brewery_map_df) +
  geom_path(aes(x = long, y = lat, group = group), color = &quot;white&quot;) +
  geom_polygon(aes(
    x = long,
    y = lat,
    group = group,
    fill = Breweries # fill the map by breweries type by state and total breweries.
  ), color = &quot;white&quot;) +
  coord_map() +
  scale_fill_gradient(low = &quot;yellow&quot; , high = &quot;orange&quot;) + #  create label color gradient
  geom_text(aes(x = long, y = lat, label = State),
            #geom_text - adds name of State into the map
            data = state_center,
            size = 3) +
  ggtitle(&quot;Breweries per State&quot;) +
  theme(
    axis.text = element_blank(),
    axis.line =  element_blank(),
    axis.ticks =  element_blank(),
    panel.border = element_blank(),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    legend.position = &quot;bottom&quot;,
    legend.title = element_text(face = &quot;bold&quot;),
    legend.direction = &quot;horizontal&quot;,
    plot.title = element_text(face = &quot;bold&quot;,
                              hjust = 0.5)
  ) # element_black : remove x- axis, y-axis lines, labels, title. Formate legneds and plot text</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-4-1.png" width="960" /></p>
</div>
<div id="question-2" class="section level2">
<h2>Question 2:</h2>
<p>Merge beer data with the breweries data. Print the first 6 observations and the last six observations to check the merged file. (RMD only, this does not need to be included in the presentation or the deck.)</p>
<p><em>We merged the two data set into one and named it as ‘mergeDF’, the primary key being used is ‘Brewery_id’ from Beer data set, and ‘Brew_ID’ from Breweries data set. We also changed the two columns’ name for clear understanding. The first and last 6 observations were showed there with head/tail command.</em></p>
<pre class="r"><code>beer_brewery_merged_df &lt;-
  full_join(beers_df, breweries_df, by = &quot;Brewery_id&quot;) # merge by  full_join  using key word  Brewery_id
head(beer_brewery_merged_df, n = 5) # view the first 5 records</code></pre>
<pre><code>##             Beer_Name Beer_ID   ABV IBU Brewery_id
## 1            Pub Beer    1436 0.050  NA        409
## 2         Devil&#39;s Cup    2265 0.066  NA        178
## 3 Rise of the Phoenix    2264 0.071  NA        178
## 4            Sinister    2263 0.090  NA        178
## 5       Sex and Candy    2262 0.075  NA        178
##                            Style Ounces              Brewery_Name City State
## 1            American Pale Lager     12 10 Barrel Brewing Company Bend    OR
## 2        American Pale Ale (APA)     12       18th Street Brewery Gary    IN
## 3                   American IPA     12       18th Street Brewery Gary    IN
## 4 American Double / Imperial IPA     12       18th Street Brewery Gary    IN
## 5                   American IPA     12       18th Street Brewery Gary    IN</code></pre>
<pre class="r"><code>tail(beer_brewery_merged_df, n = 5) # view the last 5 records</code></pre>
<pre><code>##                 Beer_Name Beer_ID   ABV IBU Brewery_id                    Style
## 2406            Belgorado     928 0.067  45        425              Belgian IPA
## 2407        Rail Yard Ale     807 0.052  NA        425 American Amber / Red Ale
## 2408      B3K Black Lager     620 0.055  NA        425              Schwarzbier
## 2409  Silverback Pale Ale     145 0.055  40        425  American Pale Ale (APA)
## 2410 Rail Yard Ale (2009)      84 0.052  NA        425 American Amber / Red Ale
##      Ounces            Brewery_Name   City State
## 2406     12 Wynkoop Brewing Company Denver    CO
## 2407     12 Wynkoop Brewing Company Denver    CO
## 2408     12 Wynkoop Brewing Company Denver    CO
## 2409     12 Wynkoop Brewing Company Denver    CO
## 2410     12 Wynkoop Brewing Company Denver    CO</code></pre>
</div>
<div id="question-3" class="section level2">
<h2>Question 3:</h2>
<p>Address the missing values in each column.</p>
<p><em>There are 62 observations where both ABV and IBU had NA values. 943 observations where the IBU only are NA’s. We replaced 62 NA’s in ABV with state level median value. Replacing 1005 NA’s in IBU with state level median led to an 18% reduction in the accuracy of the correlation model. Predicted values from simple linear regression model are used to replace missing values in IBU to improve the accuracy of the model.</em></p>
<pre class="r"><code>plot_missing(beer_brewery_merged_df,
             title = &quot;Missing Value State Post Merge of Data Sets&quot;,
             ggtheme = theme_clean())</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>#aggr(beer_brewery_merged_df, prop = FALSE, numbers = TRUE)
beer_brewery_merged_df &lt;-
  beer_brewery_merged_df %&gt;%  mutate(IBU = ifelse(is.na(IBU) |
                                                    is.na(ABV), 0, IBU)) # replace all empty and NA value by zero. Replce New IBU with New IBU using mutate()

plot_missing(beer_brewery_merged_df,
             title = &quot;Missing Values State After Cleanup of IBU&quot;,
             ggtheme = theme_clean())</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<pre class="r"><code># code added to drop ABV NA&#39;s
beer_brewery_merged_df &lt;- beer_brewery_merged_df %&gt;% drop_na(ABV)</code></pre>
</div>
<div id="question-4" class="section level2">
<h2>Question 4:</h2>
<p>Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.</p>
<p><em>Median ABV and IBU data have been sorted and plotted.</em><br />
<em>The median ABV per state appears fairly consistent with an overall ABV median of 0.056.</em><br />
<em>Nevada falls in the middle with median ABV of 0.062 and Utah is at the bottom with 0.04.</em><br />
<em>The median IBU per state appears to change considerably between states with an overall IBU median of 37.</em><br />
<em>West Virginia falls in the middle with median value 57.5 and Kansas is at the bottom with value 22.</em></p>
<p>Arkansas and Utah are tied for lowest ABV at 4.0% Maine has highest ABV at 6.7%</p>
<p>Wisconsin has the lowest IBU @ 19 Maine has the highest IBU @ 61</p>
<pre class="r"><code>## Calculate IBU and ABV median by state
ibu_median &lt;-
  beer_brewery_merged_df %&gt;% group_by(State) %&gt;% summarise_each(funs(median), median = IBU) %&gt;% arrange(median)</code></pre>
<pre><code>## Warning: funs() is soft deprecated as of dplyr 0.8.0
## Please use a list of either functions or lambdas: 
## 
##   # Simple named list: 
##   list(mean = mean, median = median)
## 
##   # Auto named with `tibble::lst()`: 
##   tibble::lst(mean, median)
## 
##   # Using lambdas
##   list(~ mean(., trim = .2), ~ median(., na.rm = TRUE))
## This warning is displayed once per session.</code></pre>
<pre class="r"><code>head(ibu_median, 5) # print first 5 IBU median</code></pre>
<pre><code>## # A tibble: 5 x 2
##   State median
##   &lt;fct&gt;  &lt;dbl&gt;
## 1 &quot; AR&quot;      0
## 2 &quot; CT&quot;      0
## 3 &quot; GA&quot;      0
## 4 &quot; IL&quot;      0
## 5 &quot; MD&quot;      0</code></pre>
<pre class="r"><code>tail(ibu_median, 5)# print last 5 IBU median</code></pre>
<pre><code>## # A tibble: 5 x 2
##   State median
##   &lt;fct&gt;  &lt;dbl&gt;
## 1 &quot; MN&quot;   38  
## 2 &quot; AL&quot;   39.5
## 3 &quot; MS&quot;   45  
## 4 &quot; DE&quot;   52  
## 5 &quot; WV&quot;   57.5</code></pre>
<pre class="r"><code>abv_median &lt;-
  beer_brewery_merged_df %&gt;% na.omit() %&gt;% group_by(State) %&gt;% summarise_each(funs(median), median = ABV) %&gt;% arrange(median) # group dataset by state and arrange them and calculate median. Apply function to ABV column.
head(abv_median, 5)</code></pre>
<pre><code>## # A tibble: 5 x 2
##   State median
##   &lt;fct&gt;  &lt;dbl&gt;
## 1 &quot; UT&quot;  0.04 
## 2 &quot; NJ&quot;  0.046
## 3 &quot; KS&quot;  0.05 
## 4 &quot; ND&quot;  0.05 
## 5 &quot; WY&quot;  0.05</code></pre>
<pre class="r"><code>tail(ibu_median, 5)</code></pre>
<pre><code>## # A tibble: 5 x 2
##   State median
##   &lt;fct&gt;  &lt;dbl&gt;
## 1 &quot; MN&quot;   38  
## 2 &quot; AL&quot;   39.5
## 3 &quot; MS&quot;   45  
## 4 &quot; DE&quot;   52  
## 5 &quot; WV&quot;   57.5</code></pre>
<pre class="r"><code>p1 &lt;-
  ggplot(ibu_median, aes(
    x = reorder(State),
    y = median,
    width = 0.5
  )) +
  geom_bar(
    stat = &quot;identity&quot;,
    fill = &quot;darkorange3&quot;,
    alpha = .6,
    width = .4
  ) +
  coord_flip() +
  ggtitle(&quot;IBU Median&quot;) +
  theme(
    panel.grid.major.y = element_blank(),
    plot.title = element_text(face = &quot;bold&quot;, size = 12),
    axis.title = element_blank()
  ) + theme(
    panel.grid.major = element_line(colour = &quot;black&quot;),
    # crate line to differentiate the bar
    panel.grid.minor = element_line(colour = &quot;black&quot;,
                                    linetype = &quot;dotted&quot;),
    axis.text = element_text(colour = &quot;black&quot;),
    plot.title = element_text(hjust = 0.5),
    # align title to the middel of chart
    legend.position = &quot;none&quot;
  ) + labs(title = &quot;Median IBU&quot;)

p2 &lt;-
  ggplot(abv_median, aes(
    x = reorder(State),
    # arrange or reoder the factor level state based on ABU value
    y = median,
    width = 0.5
  )) +
  geom_bar(
    stat = &quot;identity&quot;,
    fill = &quot;darkorange3&quot;,
    alpha = .6,
    width = .4
  ) +
  coord_flip() +
  ggtitle(&quot;ABV Median&quot;) +
  theme(
    panel.grid.major.y = element_blank(),
    plot.title = element_text(face = &quot;bold&quot;, size = 12),
    axis.title = element_blank()
  ) + theme(
    panel.grid.major = element_line(colour = &quot;black&quot;),
    panel.grid.minor = element_line(colour = &quot;black&quot;,
                                    linetype = &quot;dotted&quot;),
    axis.text = element_text(colour = &quot;black&quot;),
    plot.title = element_text(hjust = 0.5),
    # align title to middle of chart
    legend.position = &quot;none&quot;
  ) + labs(title = &quot;Median ABV&quot;)

grid.arrange(p1, p2, ncol = 2) # puts the two graph side by side</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="question-5" class="section level2">
<h2>Question 5:</h2>
<p>Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer?</p>
<p><em>Maximum ABV and IBU data have been sorted and plotted. The maximum ABV by state appears to have only a small variance. Colorado has the Maximum ABV at 0.128 and Delaware has the lowest at 0.055. The maximum IBU per state appears to vary between states with an overall median of all max values at 92.82. Oregon has the highest Max IBU at 138 and Arkansas has the lowest at 44.11</em></p>
<pre class="r"><code># find max IBU of beer and arrange by top 10
ibu_max &lt;-
  beer_brewery_merged_df %&gt;% group_by(State) %&gt;% summarise_each(funs(max), ibumax = IBU) %&gt;% arrange(-ibumax)
head(ibu_max, 5)</code></pre>
<pre><code>## # A tibble: 5 x 2
##   State ibumax
##   &lt;fct&gt;  &lt;dbl&gt;
## 1 &quot; OR&quot;    138
## 2 &quot; VA&quot;    135
## 3 &quot; MA&quot;    130
## 4 &quot; OH&quot;    126
## 5 &quot; MN&quot;    120</code></pre>
<pre class="r"><code>tail(ibu_max, 5)</code></pre>
<pre><code>## # A tibble: 5 x 2
##   State ibumax
##   &lt;fct&gt;  &lt;dbl&gt;
## 1 &quot; TN&quot;     61
## 2 &quot; LA&quot;     60
## 3 &quot; DE&quot;     52
## 4 &quot; AR&quot;     39
## 5 &quot; SD&quot;      0</code></pre>
<pre class="r"><code>ibu_top &lt;-
  ibu_max %&gt;% top_n(5, ibumax) # print top 6 state with highest IBU.
ibu_top &lt;- ibu_top[order(-ibu_top$ibumax),]

# find ABV max grouped by state
abv_max &lt;-
  beer_brewery_merged_df %&gt;% na.omit() %&gt;% group_by(State) %&gt;% summarise_each(funs(max), abvmax = ABV) %&gt;% arrange(-abvmax)
head(abv_max, 5)</code></pre>
<pre><code>## # A tibble: 5 x 2
##   State abvmax
##   &lt;fct&gt;  &lt;dbl&gt;
## 1 &quot; CO&quot;  0.128
## 2 &quot; KY&quot;  0.125
## 3 &quot; IN&quot;  0.12 
## 4 &quot; NY&quot;  0.1  
## 5 &quot; CA&quot;  0.099</code></pre>
<pre class="r"><code>tail(abv_max, 5)</code></pre>
<pre><code>## # A tibble: 5 x 2
##   State abvmax
##   &lt;fct&gt;  &lt;dbl&gt;
## 1 &quot; WV&quot;  0.067
## 2 &quot; NH&quot;  0.065
## 3 &quot; TN&quot;  0.062
## 4 &quot; AR&quot;  0.061
## 5 &quot; DE&quot;  0.055</code></pre>
<pre class="r"><code>abv_top &lt;- abv_max %&gt;% top_n(10, abvmax)
abv_top &lt;- abv_top[order(-abv_top$abvmax),]

# plot top ten state representing IBU using bar plot
ggplot(ibu_top, aes(x = State, y = ibumax, fill = ibumax)) + geom_bar(
  stat = &quot;identity&quot;,
  fill = &quot;darkorange3&quot;,
  alpha = .6,
  width = .4
) + ggtitle(&quot;Top 5 IBU by States&quot;) +
  geom_text(aes(label = ibumax), hjust = 1.5) +
  theme(
    axis.text.y = element_text(size = rel(0.8), angle = 90),
    #the function rel() modifies the size relative to the base size. angle= 90: rotate terxt 90 deg
    panel.grid.major.y = element_blank(),
    panel.grid.major = element_line(colour = &quot;black&quot;),
    panel.grid.minor = element_line(colour = &quot;black&quot;,
                                    linetype = &quot;dotted&quot;),
    axis.text = element_text(colour = &quot;black&quot;),
    plot.title = element_text(hjust = 0.5)
  ) +
  labs(x = &quot;State&quot;, y = &quot;IBU&quot;) +
  coord_flip() # flips the to horizontal form</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code>#plot top ten state representing IBU using treemap formate
treemap(
  #A Treemap displays hierarchical data as a set of nested rectangles. Each state is represented by a rectangle, which area is proportional to its IBU value
  ibu_max,
  index = c(&quot;State&quot;, &quot;ibumax&quot;),
  #vector of column names
  vSize = &quot;ibumax&quot;,
  #specifies the sizes of the rectangles (state)
  type = &quot;index&quot;,
  #ype of the treemap, which determines how the rectangles (state) are colored
  palette = &quot;Oranges&quot;,
  title = &quot;States IBU&quot;,
  fontsize.title = 14 # treemap title font size
)</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-8-2.png" width="672" /></p>
<pre class="r"><code># plot top ten state representing ABV using bar plot
ggplot(abv_top, aes(x = State, y = abvmax, fill = abvmax)) + geom_bar(
  stat = &quot;identity&quot;,
  fill = &quot;darkorange3&quot;,
  alpha = .6,
  width = .4
) + ggtitle(&quot;Top 10 ABV by States&quot;) +
  geom_text(aes(label = abvmax), hjust = 1.5) +
  theme(
    axis.text.y = element_text(size = rel(0.8), angle = 90),
    panel.grid.major.y = element_blank(),
    panel.grid.major = element_line(colour = &quot;black&quot;),
    panel.grid.minor = element_line(colour = &quot;black&quot;,
                                    linetype = &quot;dotted&quot;),
    axis.text = element_text(colour = &quot;black&quot;),
    plot.title = element_text(hjust = 0.5)
  ) +
  labs(x = &quot;State&quot;, y = &quot;ABV&quot;) +
  coord_flip()</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-8-3.png" width="672" /></p>
<pre class="r"><code>#plot top ten state representing ABV using treempa formate
treemap(
  abv_max,
  index = c(&quot;State&quot;, &quot;abvmax&quot;),
  vSize = &quot;abvmax&quot;,
  type = &quot;index&quot;,
  palette = &quot;Oranges&quot;,
  title = &quot;States ABV&quot;,
  fontsize.title = 14
)</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-8-4.png" width="672" /></p>
</div>
<div id="question-6" class="section level2">
<h2>Question 6:</h2>
<p>Comment on the summary statistics and distribution of the ABV variable.</p>
<p><em>The ABV clearly illustrates that the IPA variety has more Alcohol By Volume than other varieties. This is across all can sizes with one exception (can size=19.2) in the “other” type.</em></p>
<p><em>IPA style beer is the predominant variety when ABV exceeds 0.06. This again indicates that IPA beer tends to have higher alcohol content than other variety.</em></p>
<pre class="r"><code># Create new column for IPA/Ale breakdown
beer_brewery_merged_df$Beer_Type &lt;-
  ifelse(
    str_detect(beer_brewery_merged_df$Style, regex(&quot;IPA&quot;, ignore_case = TRUE)),
    &quot;IPA&quot;,
    # using regular expression regex() to detect and ingnore the case of IPA
    ifelse(
      str_detect(beer_brewery_merged_df$Style, regex(&quot;Ale&quot;, ignore_case = TRUE)),
      &quot;Ale&quot;,
      &quot;Other&quot;
    )
  )

##   Histogram showing the distribution of the ABV
beer_brewery_merged_df %&gt;% ggplot(aes(x = ABV)) + geom_histogram(
  fill = &quot;darkorange&quot;,
  color =
    &quot;black&quot;,
  bins = 30,
  na.rm = TRUE
) + theme(axis.text.y = element_text(size = rel(0.8), angle = 90)) +
  labs(x = NULL, y = &quot;ABV&quot;)</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>##   Bloxplot showing the variation of ABV by ounce
beer_brewery_merged_df$Ounces = as.factor(beer_brewery_merged_df$Ounces)
beer_brewery_merged_df %&gt;% ggplot(aes(y = ABV,
                                      x = Ounces, fill = Ounces)) + geom_boxplot(na.rm = TRUE) +
  theme(axis.text.y = element_text(size = rel(0.8), angle = 90)) +
  labs(x = &quot;Ounces&quot;, y = &quot;ABV&quot;) +
  ggtitle(&quot;Boxplot of ABV by Ounces&quot;)</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-9-2.png" width="672" /></p>
<pre class="r"><code># box plot showing the variation of ABV for three types: Ale, IPA and other
beer_brewery_merged_df %&gt;% ggplot(aes(y = ABV,
                                      x = Beer_Type, fill = Beer_Type)) + geom_boxplot(na.rm = TRUE) +
  theme(axis.text.y = element_text(size = rel(0.8), angle = 90)) +
  labs(x = &quot;Type&quot;, y = &quot;ABV&quot;) +
  ggtitle(&quot;Boxplot of ABV by Beer Type&quot;)</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-9-3.png" width="672" /></p>
<pre class="r"><code>summary(beer_brewery_merged_df) # display summary statistic of data</code></pre>
<pre><code>##                   Beer_Name       Beer_ID            ABV         
##  Nonstop Hef Hop       :  12   Min.   :   1.0   Min.   :0.00100  
##  Dale&#39;s Pale Ale       :   6   1st Qu.: 827.8   1st Qu.:0.05000  
##  Oktoberfest           :   6   Median :1463.5   Median :0.05600  
##  Longboard Island Lager:   4   Mean   :1439.4   Mean   :0.05977  
##  1327 Pod&#39;s ESB        :   3   3rd Qu.:2078.2   3rd Qu.:0.06700  
##  Boston Lager          :   3   Max.   :2692.0   Max.   :0.12800  
##  (Other)               :2314                                     
##       IBU           Brewery_id                               Style     
##  Min.   :  0.00   Min.   :  1.0   American IPA                  : 417  
##  1st Qu.:  0.00   1st Qu.: 94.0   American Pale Ale (APA)       : 239  
##  Median : 18.00   Median :206.0   American Amber / Red Ale      : 125  
##  Mean   : 25.56   Mean   :231.3   American Blonde Ale           : 104  
##  3rd Qu.: 42.00   3rd Qu.:366.0   American Double / Imperial IPA: 103  
##  Max.   :138.00   Max.   :558.0   American Pale Wheat Ale       :  95  
##                                   (Other)                       :1265  
##   Ounces                         Brewery_Name      City          
##  8.4 :   1   Brewery Vivant            :  60   Length:2348       
##  12  :1484   Oskar Blues Brewery       :  42   Class :character  
##  16  : 821   Sun King Brewing Company  :  36   Mode  :character  
##  16.9:   1   Cigar City Brewing Company:  25                     
##  19.2:  15   Sixpoint Craft Ales       :  24                     
##  24  :  22   Hopworks Urban Brewery    :  23                     
##  32  :   4   (Other)                   :2138                     
##      State       Beer_Type        
##   CO    : 250   Length:2348       
##   CA    : 182   Class :character  
##   MI    : 151   Mode  :character  
##   IN    : 137                     
##   OR    : 125                     
##   TX    : 124                     
##  (Other):1379</code></pre>
<pre class="r"><code>plot_intro(beer_brewery_merged_df) # metrics display using DataExplorer package</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-9-4.png" width="672" /></p>
<pre class="r"><code>introduce(beer_brewery_merged_df) # Describe basic information in input data class like: # of col , # rows etc. </code></pre>
<pre><code>##   rows columns discrete_columns continuous_columns all_missing_columns
## 1 2348      11                7                  4                   0
##   total_missing_values complete_rows total_observations memory_usage
## 1                    0          2348              25828       415840</code></pre>
</div>
<div id="question-7" class="section level2">
<h2>Question 7:</h2>
<p>Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot. Make your best judgment of a relationship and EXPLAIN your answer.</p>
<p><em>The point plot below illustrates what appears to a positive linear relationship between the ABV and IBU. The addition of line trend to the point plot below confirms the presence of a positive linear relationship between the ABV and IBU.</em></p>
<p><em>The correlation between IBU and ABV is 0.757878, with a p-value &lt; 2e-16, Multiple R-squared is 0.5744, meaning that 57% changes in exploratory variable ABV can explain the changes in response variable IBU.</em></p>
<p><em>GGPairs Plot below shows a strong correlation between ABV and IBU across all styles of beers. The strongest correlation is in other beer style category at 0.787 followed by IPA at 0.689.</em></p>
<pre class="r"><code># Scatter plot showing positive correlation between IBU and ABV
beer_brewery_merged_df %&gt;% na.omit() %&gt;% # use only data without NAs
  ggplot(aes(x = ABV, y = IBU)) +
  geom_point(aes(color = State), size = 1, position = &quot;jitter&quot;) +
  geom_smooth(method = lm) +
  theme(axis.text.y = element_text(size = rel(0.8), angle = 90),
        legend.position = &quot;none&quot;) +
  labs(x = &quot;ABV&quot;, y = &quot;IBU&quot;) +
  ggtitle(&quot;Relationship between IBU and ABV&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>#Pearson&#39;s correlation with original data
cor.test(beer_brewery_merged_df$IBU, beer_brewery_merged_df$ABV)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  beer_brewery_merged_df$IBU and beer_brewery_merged_df$ABV
## t = 19.228, df = 2346, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.3334942 0.4033996
## sample estimates:
##       cor 
## 0.3689686</code></pre>
<pre class="r"><code>mod &lt;-
  lm(beer_brewery_merged_df$IBU ~ beer_brewery_merged_df$ABV) # Create a linear model and save it into a variable mod.
summary(mod) # display summary statistic of our mod</code></pre>
<pre><code>## 
## Call:
## lm(formula = beer_brewery_merged_df$IBU ~ beer_brewery_merged_df$ABV)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -79.49 -21.00  -1.81  18.84 110.05 
## 
## Coefficients:
##                            Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                 -21.688      2.519  -8.608   &lt;2e-16 ***
## beer_brewery_merged_df$ABV  790.436     41.109  19.228   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 26.97 on 2346 degrees of freedom
## Multiple R-squared:  0.1361, Adjusted R-squared:  0.1358 
## F-statistic: 369.7 on 1 and 2346 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code># Plot GGpairs
beer_brewery_merged_df %&gt;% na.omit() %&gt;%
  select(ABV, IBU, Ounces, Beer_Type) %&gt;%
  ggpairs(mapping = aes(color = &quot;ABV&quot;))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-10-2.png" width="672" /></p>
</div>
<div id="question-8" class="section level2">
<h2>Question 8</h2>
<ol start="8" style="list-style-type: decimal">
<li>Budweiser would also like to investigate the difference with respect to IBU and ABV between IPAs (India Pale Ales) and other types of Ale (any beer with “Ale” in its name other than IPA). You decide to use KNN classification to investigate this relationship. Provide statistical evidence one way or the other. You can of course assume your audience is comfortable with percentages … KNN is very easy to understand conceptually.</li>
</ol>
<p>In addition, while you have decided to use KNN to investigate this relationship (KNN is required) you may also feel free to supplement your response to this question with any other methods or techniques you have learned. Creativity and alternative solutions are always encouraged.</p>
<pre class="r"><code># Filter out any beer style that isnt and IPA or an Ale.
beer_brewery_IPAandALE &lt;-
  filter(beer_brewery_merged_df, grepl(&#39;IPA|Ale&#39;, Style))
beer_brewery_IPAandALE &lt;- beer_brewery_IPAandALE[, -8]
# Create a new dataframe that only holds the ABV,IBU, and beer style.
beer_brewery_IPAandALE_subset &lt;-
  select(beer_brewery_IPAandALE, ABV, IBU, Style)
beer_brewery_IPAandALE_subset$Style &lt;-
  as.character(beer_brewery_IPAandALE_subset$Style) # change stye factor into character

# Normalize the Beer styles to IPA or ALE
# Loop below is used to iterate through each row and then to normalize the beer styles to simply say IPA or Ale.
for (i in 1:nrow(beer_brewery_IPAandALE_subset)) {
  if (is.na(str_match(beer_brewery_IPAandALE_subset[i, 3], &quot;.Ale&quot;))) {
    beer_brewery_IPAandALE_subset[i, 3] &lt;- &quot;IPA&quot;
  } else {
    beer_brewery_IPAandALE_subset[i, 3] &lt;- &quot;ALE&quot;
    
  }
}
# use KNN classification to investigate this relationship
# Provide statistical evidence. Your audience is comfortable with percentages.
# Select a random seed value
# A split of 70% to 30% will work with this dataset to create a useful training and test set.
set.seed(1234)
splitpale = .70
samplesplit &lt;-
  sample(1:dim(beer_brewery_IPAandALE_subset)[1],
         round(splitpale * dim(beer_brewery_IPAandALE_subset)[1]))</code></pre>
</div>
<div id="the-following-code-separates-the-randomly-selected-values-into-the-70-to-30-split." class="section level1">
<h1>The following code separates the randomly selected values into the 70 to 30 split.</h1>
<pre class="r"><code>trainIpa &lt;- beer_brewery_IPAandALE_subset[samplesplit, ]
testIpa &lt;- beer_brewery_IPAandALE_subset[-samplesplit, ]
# Using only the IBU and ABV values from both the training and test sets
# we are using the beer style as the class against which the knn will search.
knnipa &lt;-
  knn(trainIpa[, c(1:2)],
      testIpa[, c(1:2)],
      trainIpa$Style,
      k = 14,
      prob = TRUE)
# The confusion matrix is used for calibrating the output of a model and examining all possible outcomes of the predictions
table(knnipa, testIpa$Style)</code></pre>
<pre><code>##       
## knnipa ALE IPA
##    ALE 246  54
##    IPA  33 115</code></pre>
<pre class="r"><code>ipamatrix = confusionMatrix(table(knnipa, testIpa$Style))
ipamatrix</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##       
## knnipa ALE IPA
##    ALE 246  54
##    IPA  33 115
##                                           
##                Accuracy : 0.8058          
##                  95% CI : (0.7661, 0.8414)
##     No Information Rate : 0.6228          
##     P-Value [Acc &gt; NIR] : &lt; 2e-16         
##                                           
##                   Kappa : 0.5763          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.03201         
##                                           
##             Sensitivity : 0.8817          
##             Specificity : 0.6805          
##          Pos Pred Value : 0.8200          
##          Neg Pred Value : 0.7770          
##              Prevalence : 0.6228          
##          Detection Rate : 0.5491          
##    Detection Prevalence : 0.6696          
##       Balanced Accuracy : 0.7811          
##                                           
##        &#39;Positive&#39; Class : ALE             
## </code></pre>
</div>
<div id="the-below-code-will-iterate-through-100-values-of-k-in-order-to-hypertune-the-k-parameter." class="section level1">
<h1>The below code will iterate through 100 values of k in order to hypertune the k parameter.</h1>
</div>
<div id="this-is-used-to-identify-the-best-k-value-to-increase-the-accuracy-percentage" class="section level1">
<h1>This is used to identify the best K value to increase the accuracy percentage</h1>
<pre class="r"><code>accu = data.frame(accuracy = numeric(100), k = numeric(100))
for (i in 1:100) {
  classify = knn(trainIpa[, c(1, 2)],
                 testIpa[, c(1, 2)],
                 trainIpa$Style,
                 prob = TRUE,
                 k = i)
  table(classify, testIpa$Style)
  confused &lt;- confusionMatrix(table(classify, testIpa$Style))
  accu$accuracy[i] = confused$overall[1]
  accu$k[i] = i
}
accuplot &lt;- ggplot(accu, aes(x = k, y = accuracy)) +
  geom_line() +
  labs(x = &quot;Tally&quot;, y = &quot;Accuracy&quot;)
accuplot &lt;- plot(accuplot)</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>accuplot</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
</div>
<div id="question-9" class="section level1">
<h1>Question 9</h1>
</div>
<div id="find-one-other-useful-inference-from-the-data-that-you-feel-budweiser-may-be-able-to-find-value-in." class="section level1">
<h1>Find one other useful inference from the data that you feel Budweiser may be able to find value in.</h1>
</div>
<div id="you-must-convince-them-why-it-is-important-and-back-up-your-conviction-with-appropriate-statistical-evidence" class="section level1">
<h1>You must convince them why # it is important and back up your conviction with appropriate statistical evidence</h1>
</div>
<div id="create-a-bubble-chart-showing-which-states-tend-to-prefer-larger-bottles-of-beer-with-higher-abv-for-marketing-purposes." class="section level1">
<h1>Create a bubble chart showing which states tend to prefer larger bottles of beer with higher ABV for marketing purposes.</h1>
</div>
<div id="this-information-is-useful-in-that-it-can-be-used-to-target-the-beer-consumers-based-on-their-consumption-habits-and-location." class="section level1">
<h1>This information is useful in that it can be used to target the beer consumers based on their consumption habits and location.</h1>
</div>
<div id="by-visualizing-the-ounces-of-beer-bottles-and-cross-referencing-this-data-with-abv-we-are-able-to-see-a-pattern." class="section level1">
<h1>By visualizing the Ounces of beer bottles and cross referencing this data with ABV we are able to see a pattern.</h1>
</div>
<div id="the-pattern-can-then-be-layed-over-states-to-show-which-states-may-act-as-the-largest-consumers-of-beer-products." class="section level1">
<h1>The pattern can then be layed over states to show which states may act as the largest consumers of beer products.</h1>
</div>
<div id="large-lighter-blue-circles-that-sit-higher-on-the-graph-show-large-high-alcohol-content-consumption." class="section level1">
<h1>Large, lighter blue circles that sit higher on the graph show large, high alcohol content consumption.</h1>
</div>
<div id="by-tracing-the-line-down-from-such-circles-you-can-see-which-state-these-trends-exist-in." class="section level1">
<h1>By tracing the line down from such circles, you can see which state these trends exist in.</h1>
<pre class="r"><code>theme_set(theme_bw())  
g &lt;- ggplot(beer_brewery_merged_df, aes(State, ABV, color = Ounces))
market &lt;- g + geom_count(show.legend = F) +
  labs(
    subtitle = &quot;Correlate high ABV and large containers for marketing&quot;,
    y = &quot;ABV&quot;,
    x = &quot;State&quot;,
    title = &quot;Large container consumption by State&quot;
  )
market</code></pre>
<p><img src="beer_analyis_files/figure-html/unnamed-chunk-14-1.png" width="672" /> Conclusion</p>
<p># DDS- Project-01 Summary:</p>
<p>The primary objective of our project is to take two different dataset, beer data set containing a list of 2410 US crafts beers and breweries dataset containing 558 breweries an perform analysis. We transformed the data in CVS format into data frame using R-programming, inspected and analyzed the structure of the data, merged the two data frames, and performed analysis on the merged final data set.</p>
<p>As Data Scientist, it is very rare that we get to work only on a single perfect data. A large percentage of work is to accept different datasets and merge them into one final data frame before processing as it is illustrated in our project. After analyzing the data, statistical inference is then made.</p>
<p>The objective of our project is to provide some valuable information such as summary of two dataset, relation between International Bitterness Unit (IBU) and Alcohol By Volume (ABV), number of breweries in each state and how can be an important to Budweiser, and to compute the median and max IBU and ABV.</p>
<p>Based on our team’s analysis, we found that majority of breweries appears to be clustered towards the west of the Mississippi river with California and Colorado being the top two states. Why do these states mostly CO has the highest number of Breweries? Water is the secrete ingredients making CO the top state for breweries in the world and also making 2017 gold medal winner. The water alone contains about 80-90% of water chemistry needed to make the best beers. CO water has the perfect mix of magnesium, sodium, sulfates, bicarbonates and calcium which determines the hardness of water and ultimately its suitability for brewing great testing beers. Hence, we believe that Budweiser should consider thinking about CO in their next project.</p>
<p>Other state of interest, New Hampshire which we believe has the high potential for growth has the highest beer consumers due to no beer sale tax but do not have much breweries. Utah on the other hand has the lowest beer consumer and only allows ABV &lt;4 % which could be due to it being a Mormon state. We were surprised at Nevada, being the home of Las Vegas has only two breweries. North and South Dakota are lowest in the number of breweries but are one of the highest in beer consumption capita.</p>
<p>Our computation of the median IBU and ABV for each state shows that median IBU appears to vary considerably between the states. However, West Virginia falls in the middle with median IBU 37 and Arkansas at the bottom with IBU 7.8. On the other hand, median ABV per state appears somewhat consistent, with Nevada being in the middle with median ABV of 0.0669 which kind of make sense because people who visit Las Vegas majority of the time likes to get drunk, gamble and enjoy their time. Utah again, being the lowest beer consumer also has the lowest ABV of 0.051. In term of Max ABV, all the state appears to have only a small variance. Colorado has the max ABV of 0.128 and Delaware the lowest at 0.055.</p>
<p>IBU which stands for International Bitterness Units, a measure of the bitterness in beer. There is a saying spicier the better, same applies to the beers as well. Bitter the beer better is the taste. The bitterness in beer terms mean better flavor which is produced by adding aroma hop flowers. According to CNBC news, the reason for rise in craft beer sales is its high IBU among the home brewing company that’s growing from garage to thriving commercial company. Our analysis shows that max IBU by states appears to vary between the state ranging from 138 to 0, with Oregon being the highest (138) and Arkansas the lowest (44.11). The reason we believe Oregon has the highest IBU is because Oregon is known for homemade craft beer and they also add high-grade marijuana in their craft beers. However, according to new law, started in Jan 2020, they are avoiding THC or CBD in their beers due to health concern. Arkansas stands at the bottom for IBU.</p>
<p>In a nutshell, our analysis of relationship between ABV and IBU shows that there is somewhat positive linear relation. In general, as the ABV rises so does the bitterness. IPA type has the highest ABV compared to other type also higher the Ounces higher the ABV.</p>
<p>Ref: <a href="https://www.cnbc.com/2014/07/03/state-of-hopiness-how-many-ibus-in-your-ipa.html" class="uri">https://www.cnbc.com/2014/07/03/state-of-hopiness-how-many-ibus-in-your-ipa.html</a> <a href="https://apnews.com/640bcd2970430a6cdaa7c37166dac1c9S" class="uri">https://apnews.com/640bcd2970430a6cdaa7c37166dac1c9S</a> ```</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
